### ISSUE TITLE
SSH Files missing

### ISSUE THREAD

**Issue by samlanzz** [8gears/workshop-vm#1]
Following the VM installation guide, I come across this error message upon executing the `vagrant up` command in the "Install Workshop VM" step:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /Users/myUser/.ssh/id_rsa must exist
* File upload source file /Users/myUser/.ssh/id_rsa.pub must exist
```
Do these files have to be generated by hand, or do they have to copied over from somewhere...?
The verbose `vagrant up` output is attached.
[vagrant-verbose-output.txt](https://github.com/8gears/workshop-vm/files/1259747/vagrant-verbose-output.txt)

**Comment by Vad1mo** [comment]
Seems like the files it tries to copy aren't there in your home. 
I updated the Vagrant file and now upload of ssh key is optional. You can try the latest the problem should be gone.

**Comment by samlanzz** [comment]
Works as expected now.
