### ISSUE TITLE
Error cloning 

### ISSUE THREAD

**Issue by Swanson-L** [8gears/workshop-vm#2]
Here's what happens when I try to clone either from the command window or from my IntelliJ:

> git clone https://github.com/8gears/workshop-vm.git
Cloning into 'workshop-vm'...
fatal: unable to access 'https://github.com/8gears/workshop-vm.git/': Failed connect to github.com:8080; No error

I can access the page with a browser. Thinking that the contents of the "provision" directory where what the clone was supposed to copy, I tried the vagrant up command from that directory and got the following message:

>cd provision
>vagrant up
Bringing machine 'workshopvm' up with 'virtualbox' provider...
==> workshopvm: Box 'boxcutter/ubuntu1604-desktop' could not be found. Attempting to find and install...
    workshopvm: Box Provider: virtualbox
    workshopvm: Box Version: >= 0
The box 'boxcutter/ubuntu1604-desktop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
URL: ["https://vagrantcloud.com/boxcutter/ubuntu1604-desktop"]
Error: Failed to connect to vagrantcloud.com port 443: Timed out

Any suggestions?

Larry

**Comment by Vad1mo** [comment]
Did you try via SSH

```sh
> git clone git@github.com:8gears/workshop-vm.git
```

Btw. are you behind a proxy? it seems your are not able to access https://vagrantcloud.com/boxcutter/ubuntu1604-desktop

**Comment by Swanson-L** [comment]
Thanks for answering.

 

> git clone  <mailto:git@github.com:8gears/workshop-vm.git> git@github.com:8gears/workshop-vm.git

 

Caused the following:

 

Cloning into 'workshop-vm'...

The authenticity of host 'github.com (192.30.253.112)' can't be established.

RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.

Are you sure you want to continue connecting (yes/no)? yes

Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

 

Please make sure you have the correct access rights

and the repository exists.

 

>Btw. do you have any proxy settings?

Yes, we have a proxy set up.

 

A colleague was able to help me work around the problem.

 

Thanks and regards,

 

Larry

 

Von: Vadim Bauer [mailto:notifications@github.com] 
Gesendet: Dienstag, 29. August 2017 15:58
An: 8gears/workshop-vm <workshop-vm@noreply.github.com>
Cc: Swanson Lawrence BIT <lawrence.swanson@bit.admin.ch>; Author <author@noreply.github.com>
Betreff: Re: [8gears/workshop-vm] Error cloning (#2)

 

Did you try via SSH

> git clone git@github.com:8gears/workshop-vm.git <mailto:git@github.com:8gears/workshop-vm.git> 

Btw. do you have any proxy settings?
