### ISSUE TITLE
Ubuntu boots up to an empty desktop

### ISSUE THREAD

**Issue by fmehta** [8gears/workshop-vm#3]
Hi,

After following the instructions, the Ubuntu VM boots up to an empty desktop (i.e. no menubar, no desktop icons, etc.) The right click works though, and it can brung up a terminal.

Is this normal?

Setup: MacOSX 10.12.6 with the latest versions of VirtualBox and Vagrant installed from the respective website distributions (i.e. not with Homebrew)

Best regards,
Farhad

**Comment by Vad1mo** [comment]
The normal Ubuntu Unity Desktop should pop up. 

Like this.
![image](https://user-images.githubusercontent.com/1492007/29841371-80161178-8d05-11e7-9c4b-5ef51a52fec3.png)


Can you paste the log output form the command line after you did `vagrant up`?

**Comment by fmehta** [comment]
Hi
Thanks for your reply. I installed the VM again and it seems to work as expected now. Thanks for the quick answer.

Farhad
