### ISSUE TITLE
The box 'boxcutter/ubuntu1604-desktop' could not be found

### ISSUE THREAD

**Issue by rbadert** [8gears/workshop-vm#4]
Bringing machine 'workshopvm' up with 'virtualbox' provider...
==> workshopvm: Box 'boxcutter/ubuntu1604-desktop' could not be found. Attempting to find and install...
    workshopvm: Box Provider: virtualbox
    workshopvm: Box Version: >= 0
The box 'boxcutter/ubuntu1604-desktop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/boxcutter/ubuntu1604-desktop"]
Error: The requested URL returned error: 404 Not Found

Regards

Reto

**Comment by Vad1mo** [comment]
Seems there is some chaos going on in the image we use. https://github.com/boxcutter/ubuntu/issues/124

I updated the reference in the Vagrantfile. 

Can you give it a try?

**Comment by rbadert** [comment]
Thanks - works with the updated Vagrantfile.

Have a nice day

Reto
